"use client";

import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Check, Terminal } from "lucide-react";

interface Bucket {
  range: string;
  midpoint: number;
  meanPredicted: number;
  actualHitRate: number;
  n: number;
  residual: number;
}

interface BacktestReportData {
  generatedAt: string;
  totalPicks: number;
  buckets: Bucket[];
  byOddsType: { standard: Bucket[]; goblin: Bucket[]; demon: Bucket[] };
  perStat: Record<string, { n: number; hitRate: number; meanPredicted: number; residual: number }>;
  syntheticPL: {
    pickCount: number;
    hits: number;
    overallHitRate: number;
    meanPredicted: number;
    meanResidual: number;
  };
}

interface CalibrationData {
  fittedAt: string;
  trainingSize: number;
  breakpoints: Array<{ predicted: number; corrected: number }>;
}

interface ApiResponse {
  available: boolean;
  reason?: string;
  report?: BacktestReportData;
  calibration?: CalibrationData | null;
}

/**
 * Reads the latest backtest report from /api/backtest/report and renders
 * the calibration breakdown. The report file lives on disk and is
 * (re)generated by `npx tsx scripts/backtest.ts`.
 *
 * The point of this panel: tell the user where the heuristic model
 * over- and under-confides. A perfectly calibrated model has residual
 * 0 in every bucket. A model that says 80% but hits 60% has a -20%
 * residual — that's exactly the kind of leak the isotonic corrector
 * (calibration.json) is built to close.
 */
export function BacktestReport() {
  const [data, setData] = useState<ApiResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/backtest/report");
        if (!res.ok || cancelled) return;
        const body = (await res.json()) as ApiResponse;
        if (!cancelled) setData(body);
      } catch {
        if (!cancelled) setData({ available: false, reason: "Failed to load report." });
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <section className="rounded-3xl border-4 border-[#7B2FFF] bg-gradient-to-br from-[#7B2FFF]/10 via-[#FF3AF2]/10 to-[#00F5D4]/10 p-6 md:p-8">
      <div className="flex items-start gap-3 flex-wrap mb-4">
        <div className="w-12 h-12 rounded-2xl bg-[#7B2FFF] flex items-center justify-center flex-shrink-0">
          <Activity size={26} strokeWidth={3} className="text-white" aria-hidden />
        </div>
        <div className="flex-1 min-w-[220px]">
          <h2 className="font-[family-name:var(--font-heading)] font-black uppercase tracking-tighter text-2xl md:text-3xl text-white leading-none">
            Backtest report
          </h2>
          <p className="text-white/65 text-sm mt-2 max-w-2xl">
            Synthetic-line backtest of the heuristic projection model against the 2025-26 NBA
            season. Reads the most recent run from disk. Re-run anytime via{" "}
            <code className="px-1.5 py-0.5 rounded bg-[#0D0D1A] text-[#00F5D4] text-xs">
              npx tsx scripts/backtest.ts
            </code>
            .
          </p>
        </div>
      </div>

      {loading && (
        <div className="text-white/55 text-sm">Loading…</div>
      )}

      {!loading && data && !data.available && (
        <EmptyState reason={data.reason} />
      )}

      {!loading && data?.available && data.report && (
        <Body report={data.report} calibration={data.calibration ?? null} />
      )}
    </section>
  );
}

function EmptyState({ reason }: { reason?: string }) {
  return (
    <div className="mt-4 rounded-2xl border-2 border-dashed border-white/15 p-6 text-center">
      <Terminal size={28} strokeWidth={2.5} className="mx-auto text-white/40 mb-3" aria-hidden />
      <div className="font-[family-name:var(--font-heading)] font-black uppercase tracking-widest text-white/65 text-sm">
        No report yet
      </div>
      <p className="text-white/45 text-xs mt-2 max-w-md mx-auto leading-relaxed">
        {reason ?? "Run the backtest first:"}
      </p>
      <code className="inline-block mt-3 px-3 py-2 rounded-lg bg-[#0D0D1A] text-[#00F5D4] text-xs font-mono">
        npx tsx scripts/backtest.ts
      </code>
      <p className="text-white/35 text-[10px] mt-3 max-w-md mx-auto">
        Fetches every NBA player&apos;s 2025-26 gamelog from ESPN, synthesizes lines, runs the
        heuristic model, dumps the calibration JSON. First run is ~5-8 min; subsequent
        runs hit the gamelog cache and finish in seconds.
      </p>
    </div>
  );
}

function Body({
  report,
  calibration,
}: {
  report: BacktestReportData;
  calibration: CalibrationData | null;
}) {
  const generatedLabel = new Date(report.generatedAt).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
  return (
    <>
      {/* Summary tiles */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 mt-5 mb-5">
        <SummaryTile label="Picks evaluated" value={report.totalPicks.toLocaleString()} accent="#00F5D4" />
        <SummaryTile
          label="Mean predicted"
          value={`${(report.syntheticPL.meanPredicted * 100).toFixed(1)}%`}
          accent="#FFE600"
        />
        <SummaryTile
          label="Actual hit rate"
          value={`${(report.syntheticPL.overallHitRate * 100).toFixed(1)}%`}
          accent={residualColor(report.syntheticPL.meanResidual)}
        />
        <SummaryTile
          label="Global residual"
          value={`${report.syntheticPL.meanResidual >= 0 ? "+" : ""}${(report.syntheticPL.meanResidual * 100).toFixed(1)}%`}
          accent={residualColor(report.syntheticPL.meanResidual)}
          sub={
            Math.abs(report.syntheticPL.meanResidual) < 0.02
              ? "well calibrated"
              : report.syntheticPL.meanResidual > 0
                ? "underconfident"
                : "overconfident"
          }
        />
      </div>

      {/* Main calibration table */}
      <div className="mt-2">
        <h3 className="text-white/75 text-xs uppercase tracking-widest font-bold mb-3">
          Calibration buckets · overall
        </h3>
        <CalibrationTable buckets={report.buckets} />
      </div>

      {/* Per-oddsType breakouts */}
      <div className="mt-6 grid grid-cols-1 lg:grid-cols-3 gap-4">
        <OddsTypeSection title="Standard" buckets={report.byOddsType.standard} />
        <OddsTypeSection title="Goblin" buckets={report.byOddsType.goblin} />
        <OddsTypeSection title="Demon" buckets={report.byOddsType.demon} />
      </div>

      {/* Per-stat */}
      <div className="mt-6">
        <h3 className="text-white/75 text-xs uppercase tracking-widest font-bold mb-3">
          By stat type
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
          {Object.entries(report.perStat)
            .sort((a, b) => b[1].n - a[1].n)
            .map(([stat, row]) => (
              <div
                key={stat}
                className="rounded-lg border border-white/10 bg-[#0D0D1A]/60 px-3 py-2 flex items-center justify-between"
              >
                <div>
                  <div className="text-white/85 text-xs font-bold">{stat}</div>
                  <div className="text-white/40 text-[10px]">{row.n.toLocaleString()} picks</div>
                </div>
                <div className="text-right">
                  <div className="text-[10px] text-white/45">pred / actual</div>
                  <div className="text-white/85 text-xs font-mono">
                    {(row.meanPredicted * 100).toFixed(1)}% / {(row.hitRate * 100).toFixed(1)}%
                  </div>
                  <div
                    className="text-[10px] font-mono"
                    style={{ color: residualColor(row.residual) }}
                  >
                    {row.residual >= 0 ? "+" : ""}{(row.residual * 100).toFixed(1)}%
                  </div>
                </div>
              </div>
            ))}
        </div>
      </div>

      {/* Calibration model footer */}
      <div className="mt-6 rounded-xl border-2 border-[#00F5D4]/40 bg-[#00F5D4]/5 p-4 text-sm flex items-start gap-3">
        {calibration ? (
          <>
            <Check size={18} strokeWidth={3} className="text-[#4ADE80] flex-shrink-0 mt-0.5" aria-hidden />
            <div className="flex-1">
              <div className="text-[#4ADE80] font-bold mb-0.5">
                Calibration fit · {calibration.breakpoints.length} breakpoints from{" "}
                {calibration.trainingSize.toLocaleString()} picks
              </div>
              <div className="text-white/55 text-xs">
                Written to <code className="text-[#00F5D4]">data/backtest/calibration.json</code>.
                The live model can apply this corrector once you toggle{" "}
                <strong className="text-white/80">Settings → Calibration enabled</strong>. Off
                by default until you&apos;ve reviewed the buckets above.
              </div>
            </div>
          </>
        ) : (
          <>
            <AlertTriangle size={18} strokeWidth={3} className="text-[#F87171] flex-shrink-0 mt-0.5" aria-hidden />
            <div className="text-white/65">
              No calibration model alongside this report. Re-run the script to refit.
            </div>
          </>
        )}
      </div>

      <p className="text-white/35 text-[10px] mt-3">Last run: {generatedLabel}</p>
    </>
  );
}

function SummaryTile({
  label,
  value,
  sub,
  accent,
}: {
  label: string;
  value: string;
  sub?: string;
  accent: string;
}) {
  return (
    <div
      className="rounded-xl border-2 px-3 py-2.5 bg-[#0D0D1A]/60"
      style={{ borderColor: `${accent}60` }}
    >
      <div className="text-[9px] uppercase tracking-widest font-bold mb-1" style={{ color: accent }}>
        {label}
      </div>
      <div className="font-[family-name:var(--font-heading)] font-black text-white text-base md:text-lg">
        {value}
      </div>
      {sub && (
        <div className="text-white/45 text-[10px] mt-0.5 uppercase tracking-widest font-bold">
          {sub}
        </div>
      )}
    </div>
  );
}

function CalibrationTable({ buckets }: { buckets: Bucket[] }) {
  return (
    <div className="rounded-xl border border-white/10 bg-[#0D0D1A]/60 overflow-hidden">
      <table className="w-full text-sm font-mono">
        <thead className="bg-white/5 text-white/55 text-[10px] uppercase tracking-widest font-bold">
          <tr>
            <th className="text-left px-3 py-2">Bucket</th>
            <th className="text-right px-3 py-2">Predicted</th>
            <th className="text-right px-3 py-2">Actual</th>
            <th className="text-right px-3 py-2">Residual</th>
            <th className="text-right px-3 py-2">n</th>
          </tr>
        </thead>
        <tbody>
          {buckets.map((b) => (
            <tr key={b.range} className="border-t border-white/5">
              <td className="px-3 py-2 text-white/80">{b.range}</td>
              <td className="px-3 py-2 text-right text-white/85">
                {b.n === 0 ? "—" : `${(b.meanPredicted * 100).toFixed(1)}%`}
              </td>
              <td className="px-3 py-2 text-right text-white/85">
                {b.n === 0 ? "—" : `${(b.actualHitRate * 100).toFixed(1)}%`}
              </td>
              <td
                className="px-3 py-2 text-right font-bold"
                style={{ color: residualColor(b.residual) }}
              >
                {b.n === 0
                  ? "—"
                  : `${b.residual >= 0 ? "+" : ""}${(b.residual * 100).toFixed(1)}%`}
              </td>
              <td className="px-3 py-2 text-right text-white/55">{b.n.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function OddsTypeSection({ title, buckets }: { title: string; buckets: Bucket[] }) {
  const totalN = buckets.reduce((s, b) => s + b.n, 0);
  return (
    <div className="rounded-xl border border-white/10 bg-[#0D0D1A]/40 p-3">
      <div className="flex items-center justify-between mb-2">
        <h4 className="text-white/80 text-[11px] uppercase tracking-widest font-bold">{title}</h4>
        <span className="text-white/40 text-[10px]">{totalN.toLocaleString()} picks</span>
      </div>
      <div className="space-y-1 text-xs font-mono">
        {buckets.map((b) => (
          <div key={b.range} className="flex justify-between items-center gap-2">
            <span className="text-white/55 text-[10px]">{b.range}</span>
            {b.n === 0 ? (
              <span className="text-white/30">—</span>
            ) : (
              <motion.span
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="font-bold"
                style={{ color: residualColor(b.residual) }}
              >
                {b.residual >= 0 ? "+" : ""}{(b.residual * 100).toFixed(1)}%
              </motion.span>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

/** Green when |residual| < 2%, yellow 2-5%, red ≥5%. Matches the rest of
 *  the app's traffic-light convention. */
function residualColor(residual: number): string {
  const abs = Math.abs(residual);
  if (abs < 0.02) return "#4ADE80";
  if (abs < 0.05) return "#FFE600";
  return "#F87171";
}

