"use client";

import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Check, Terminal } from "lucide-react";

interface Bucket {
  range: string;
  midpoint: number;
  meanPredicted: number;
  actualHitRate: number;
  n: number;
  residual: number;
}

interface BacktestReportData {
  generatedAt: string;
  totalPicks: number;
  buckets: Bucket[];
  byOddsType: { standard: Bucket[]; goblin: Bucket[]; demon: Bucket[] };
  perStat: Record<string, { n: number; hitRate: number; meanPredicted: number; residual: number }>;
  syntheticPL: {
    pickCount: number;
    hits: number;
    overallHitRate: number;
    meanPredicted: number;
    meanResidual: number;
  };
}

/** Legacy single-curve shape. */
interface SingleCalibrationData {
  fittedAt: string;
  trainingSize: number;
  breakpoints: Array<{ predicted: number; corrected: number }>;
}

/** Per-oddsType shape — fit on standard / goblin / demon separately. */
interface MultiOddsCalibrationData {
  fittedAt: string;
  trainingSize: number;
  all: SingleCalibrationData;
  standard: SingleCalibrationData;
  goblin: SingleCalibrationData;
  demon: SingleCalibrationData;
}

/** Current per-stat × per-oddsType shape. */
interface PerStatCalibrationData {
  fittedAt: string;
  trainingSize: number;
  all: SingleCalibrationData;
  byOddsType: Record<"standard" | "goblin" | "demon", SingleCalibrationData>;
  byStatOdds: Record<string, Record<"standard" | "goblin" | "demon", SingleCalibrationData>>;
}

type CalibrationData =
  | SingleCalibrationData
  | MultiOddsCalibrationData
  | PerStatCalibrationData;

function isMultiOdds(c: CalibrationData): c is MultiOddsCalibrationData {
  return "all" in c && "standard" in c && "goblin" in c && "demon" in c && !("byStatOdds" in c);
}

function isPerStat(c: CalibrationData): c is PerStatCalibrationData {
  return "byStatOdds" in c && "byOddsType" in c;
}

interface CVBucket {
  range: string;
  meanResidual: number;
  stdResidual: number;
  foldNs: number[];
}
interface CVData {
  folds: number;
  totalPairs: number;
  buckets: CVBucket[];
  globalMeanResidual: number;
  globalStdResidual: number;
}

interface WalkForwardMonth {
  month: string;
  trainSize: number;
  evalSize: number;
  meanPredicted: number;
  actualHitRate: number;
  residual: number;
}
interface WalkForwardData {
  generatedAt: string;
  months: WalkForwardMonth[];
  meanAbsResidual: number;
}

interface ApiResponse {
  available: boolean;
  reason?: string;
  report?: BacktestReportData;
  calibration?: CalibrationData | null;
  crossValidation?: CVData | null;
  walkForward?: WalkForwardData | null;
}

/**
 * Reads the latest backtest report from /api/backtest/report and renders
 * the calibration breakdown. The report file lives on disk and is
 * (re)generated by `npx tsx scripts/backtest.ts`.
 *
 * The point of this panel: tell the user where the heuristic model
 * over- and under-confides. A perfectly calibrated model has residual
 * 0 in every bucket. A model that says 80% but hits 60% has a -20%
 * residual — that's exactly the kind of leak the isotonic corrector
 * (calibration.json) is built to close.
 */
export function BacktestReport() {
  const [data, setData] = useState<ApiResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch("/api/backtest/report");
        if (!res.ok || cancelled) return;
        const body = (await res.json()) as ApiResponse;
        if (!cancelled) setData(body);
      } catch {
        if (!cancelled) setData({ available: false, reason: "Failed to load report." });
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <section className="rounded-3xl border-4 border-[#7B2FFF] bg-gradient-to-br from-[#7B2FFF]/10 via-[#FF3AF2]/10 to-[#00F5D4]/10 p-6 md:p-8">
      <div className="flex items-start gap-3 flex-wrap mb-4">
        <div className="w-12 h-12 rounded-2xl bg-[#7B2FFF] flex items-center justify-center flex-shrink-0">
          <Activity size={26} strokeWidth={3} className="text-white" aria-hidden />
        </div>
        <div className="flex-1 min-w-[220px]">
          <h2 className="font-[family-name:var(--font-heading)] font-black uppercase tracking-tighter text-2xl md:text-3xl text-white leading-none">
            Backtest report
          </h2>
          <p className="text-white/65 text-sm mt-2 max-w-2xl">
            Synthetic-line backtest of the heuristic projection model against the 2025-26 NBA
            season. Reads the most recent run from disk. Re-run anytime via{" "}
            <code className="px-1.5 py-0.5 rounded bg-[#0D0D1A] text-[#00F5D4] text-xs">
              npx tsx scripts/backtest.ts
            </code>
            .
          </p>
        </div>
      </div>

      {loading && (
        <div className="text-white/55 text-sm">Loading…</div>
      )}

      {!loading && data && !data.available && (
        <EmptyState reason={data.reason} />
      )}

      {!loading && data?.available && data.report && (
        <Body
          report={data.report}
          calibration={data.calibration ?? null}
          crossValidation={data.crossValidation ?? null}
          walkForward={data.walkForward ?? null}
        />
      )}
    </section>
  );
}

function EmptyState({ reason }: { reason?: string }) {
  return (
    <div className="mt-4 rounded-2xl border-2 border-dashed border-white/15 p-6 text-center">
      <Terminal size={28} strokeWidth={2.5} className="mx-auto text-white/40 mb-3" aria-hidden />
      <div className="font-[family-name:var(--font-heading)] font-black uppercase tracking-widest text-white/65 text-sm">
        No report yet
      </div>
      <p className="text-white/45 text-xs mt-2 max-w-md mx-auto leading-relaxed">
        {reason ?? "Run the backtest first:"}
      </p>
      <code className="inline-block mt-3 px-3 py-2 rounded-lg bg-[#0D0D1A] text-[#00F5D4] text-xs font-mono">
        npx tsx scripts/backtest.ts
      </code>
      <p className="text-white/35 text-[10px] mt-3 max-w-md mx-auto">
        Fetches every NBA player&apos;s 2025-26 gamelog from ESPN, synthesizes lines, runs the
        heuristic model, dumps the calibration JSON. First run is ~5-8 min; subsequent
        runs hit the gamelog cache and finish in seconds.
      </p>
    </div>
  );
}

function Body({
  report,
  calibration,
  crossValidation,
  walkForward,
}: {
  report: BacktestReportData;
  calibration: CalibrationData | null;
  crossValidation: CVData | null;
  walkForward: WalkForwardData | null;
}) {
  const generatedLabel = new Date(report.generatedAt).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
  return (
    <>
      {/* Summary tiles */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 mt-5 mb-5">
        <SummaryTile label="Picks evaluated" value={report.totalPicks.toLocaleString()} accent="#00F5D4" />
        <SummaryTile
          label="Mean predicted"
          value={`${(report.syntheticPL.meanPredicted * 100).toFixed(1)}%`}
          accent="#FFE600"
        />
        <SummaryTile
          label="Actual hit rate"
          value={`${(report.syntheticPL.overallHitRate * 100).toFixed(1)}%`}
          accent={residualColor(report.syntheticPL.meanResidual)}
        />
        <SummaryTile
          label="Global residual"
          value={`${report.syntheticPL.meanResidual >= 0 ? "+" : ""}${(report.syntheticPL.meanResidual * 100).toFixed(1)}%`}
          accent={residualColor(report.syntheticPL.meanResidual)}
          sub={
            Math.abs(report.syntheticPL.meanResidual) < 0.02
              ? "well calibrated"
              : report.syntheticPL.meanResidual > 0
                ? "underconfident"
                : "overconfident"
          }
        />
      </div>

      {/* Main calibration table */}
      <div className="mt-2">
        <h3 className="text-white/75 text-xs uppercase tracking-widest font-bold mb-3">
          Calibration buckets · overall
        </h3>
        <CalibrationTable buckets={report.buckets} />
      </div>

      {/* 5-fold CV (post-calibration stability) */}
      {crossValidation && crossValidation.folds > 0 && (
        <CrossValidationSection cv={crossValidation} />
      )}

      {/* Walk-forward drift chart */}
      {walkForward && walkForward.months.length > 0 && (
        <WalkForwardSection wf={walkForward} />
      )}

      {/* Per-oddsType breakouts */}
      <div className="mt-6 grid grid-cols-1 lg:grid-cols-3 gap-4">
        <OddsTypeSection title="Standard" buckets={report.byOddsType.standard} />
        <OddsTypeSection title="Goblin" buckets={report.byOddsType.goblin} />
        <OddsTypeSection title="Demon" buckets={report.byOddsType.demon} />
      </div>

      {/* Per-stat */}
      <div className="mt-6">
        <h3 className="text-white/75 text-xs uppercase tracking-widest font-bold mb-3">
          By stat type
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
          {Object.entries(report.perStat)
            .sort((a, b) => b[1].n - a[1].n)
            .map(([stat, row]) => (
              <div
                key={stat}
                className="rounded-lg border border-white/10 bg-[#0D0D1A]/60 px-3 py-2 flex items-center justify-between"
              >
                <div>
                  <div className="text-white/85 text-xs font-bold">{stat}</div>
                  <div className="text-white/40 text-[10px]">{row.n.toLocaleString()} picks</div>
                </div>
                <div className="text-right">
                  <div className="text-[10px] text-white/45">pred / actual</div>
                  <div className="text-white/85 text-xs font-mono">
                    {(row.meanPredicted * 100).toFixed(1)}% / {(row.hitRate * 100).toFixed(1)}%
                  </div>
                  <div
                    className="text-[10px] font-mono"
                    style={{ color: residualColor(row.residual) }}
                  >
                    {row.residual >= 0 ? "+" : ""}{(row.residual * 100).toFixed(1)}%
                  </div>
                </div>
              </div>
            ))}
        </div>
      </div>

      {/* Calibration model footer */}
      <div className="mt-6 rounded-xl border-2 border-[#00F5D4]/40 bg-[#00F5D4]/5 p-4 text-sm flex items-start gap-3">
        {calibration ? (
          <>
            <Check size={18} strokeWidth={3} className="text-[#4ADE80] flex-shrink-0 mt-0.5" aria-hidden />
            <div className="flex-1">
              <div className="text-[#4ADE80] font-bold mb-0.5">
                {isPerStat(calibration) ? (
                  <>
                    Per-stat × per-oddsType calibration · {Object.keys(calibration.byStatOdds).length} stat cells
                    <span className="text-white/55 text-xs font-normal ml-2">
                      · all: {calibration.all.breakpoints.length}bp
                      · std: {calibration.byOddsType.standard.breakpoints.length}bp
                      · gob: {calibration.byOddsType.goblin.breakpoints.length}bp
                      · dem: {calibration.byOddsType.demon.breakpoints.length}bp
                      · from {calibration.trainingSize.toLocaleString()} picks
                    </span>
                  </>
                ) : isMultiOdds(calibration) ? (
                  <>
                    Per-oddsType calibration fit from {calibration.trainingSize.toLocaleString()} picks
                    <span className="text-white/55 text-xs font-normal ml-2">
                      · all: {calibration.all.breakpoints.length}bp
                      · std: {calibration.standard.breakpoints.length}bp
                      · gob: {calibration.goblin.breakpoints.length}bp
                      · dem: {calibration.demon.breakpoints.length}bp
                    </span>
                  </>
                ) : (
                  <>
                    Calibration fit · {calibration.breakpoints.length} breakpoints from{" "}
                    {calibration.trainingSize.toLocaleString()} picks
                  </>
                )}
              </div>
              <div className="text-white/55 text-xs">
                Live model applies this corrector by default to every NBA projection. Toggle off in
                Settings if you ever need raw heuristic output. Written to{" "}
                <code className="text-[#00F5D4]">data/backtest/calibration.json</code>.
              </div>
            </div>
          </>
        ) : (
          <>
            <AlertTriangle size={18} strokeWidth={3} className="text-[#F87171] flex-shrink-0 mt-0.5" aria-hidden />
            <div className="text-white/65">
              No calibration model alongside this report. Re-run the script to refit.
            </div>
          </>
        )}
      </div>

      <p className="text-white/35 text-[10px] mt-3">Last run: {generatedLabel}</p>
    </>
  );
}

function SummaryTile({
  label,
  value,
  sub,
  accent,
}: {
  label: string;
  value: string;
  sub?: string;
  accent: string;
}) {
  return (
    <div
      className="rounded-xl border-2 px-3 py-2.5 bg-[#0D0D1A]/60"
      style={{ borderColor: `${accent}60` }}
    >
      <div className="text-[9px] uppercase tracking-widest font-bold mb-1" style={{ color: accent }}>
        {label}
      </div>
      <div className="font-[family-name:var(--font-heading)] font-black text-white text-base md:text-lg">
        {value}
      </div>
      {sub && (
        <div className="text-white/45 text-[10px] mt-0.5 uppercase tracking-widest font-bold">
          {sub}
        </div>
      )}
    </div>
  );
}

function CalibrationTable({ buckets }: { buckets: Bucket[] }) {
  return (
    <div className="rounded-xl border border-white/10 bg-[#0D0D1A]/60 overflow-hidden">
      <table className="w-full text-sm font-mono">
        <thead className="bg-white/5 text-white/55 text-[10px] uppercase tracking-widest font-bold">
          <tr>
            <th className="text-left px-3 py-2">Bucket</th>
            <th className="text-right px-3 py-2">Predicted</th>
            <th className="text-right px-3 py-2">Actual</th>
            <th className="text-right px-3 py-2">Residual</th>
            <th className="text-right px-3 py-2">n</th>
          </tr>
        </thead>
        <tbody>
          {buckets.map((b) => (
            <tr key={b.range} className="border-t border-white/5">
              <td className="px-3 py-2 text-white/80">{b.range}</td>
              <td className="px-3 py-2 text-right text-white/85">
                {b.n === 0 ? "—" : `${(b.meanPredicted * 100).toFixed(1)}%`}
              </td>
              <td className="px-3 py-2 text-right text-white/85">
                {b.n === 0 ? "—" : `${(b.actualHitRate * 100).toFixed(1)}%`}
              </td>
              <td
                className="px-3 py-2 text-right font-bold"
                style={{ color: residualColor(b.residual) }}
              >
                {b.n === 0
                  ? "—"
                  : `${b.residual >= 0 ? "+" : ""}${(b.residual * 100).toFixed(1)}%`}
              </td>
              <td className="px-3 py-2 text-right text-white/55">{b.n.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function OddsTypeSection({ title, buckets }: { title: string; buckets: Bucket[] }) {
  const totalN = buckets.reduce((s, b) => s + b.n, 0);
  return (
    <div className="rounded-xl border border-white/10 bg-[#0D0D1A]/40 p-3">
      <div className="flex items-center justify-between mb-2">
        <h4 className="text-white/80 text-[11px] uppercase tracking-widest font-bold">{title}</h4>
        <span className="text-white/40 text-[10px]">{totalN.toLocaleString()} picks</span>
      </div>
      <div className="space-y-1 text-xs font-mono">
        {buckets.map((b) => (
          <div key={b.range} className="flex justify-between items-center gap-2">
            <span className="text-white/55 text-[10px]">{b.range}</span>
            {b.n === 0 ? (
              <span className="text-white/30">—</span>
            ) : (
              <motion.span
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="font-bold"
                style={{ color: residualColor(b.residual) }}
              >
                {b.residual >= 0 ? "+" : ""}{(b.residual * 100).toFixed(1)}%
              </motion.span>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

/** Green when |residual| < 2%, yellow 2-5%, red ≥5%. Matches the rest of
 *  the app's traffic-light convention. */
function residualColor(residual: number): string {
  const abs = Math.abs(residual);
  if (abs < 0.02) return "#4ADE80";
  if (abs < 0.05) return "#FFE600";
  return "#F87171";
}

// ════════════════════════════════════════════════════════════════════
// 5-fold cross-validation panel
// ════════════════════════════════════════════════════════════════════

function CrossValidationSection({ cv }: { cv: CVData }) {
  const globalAbs = Math.abs(cv.globalMeanResidual);
  return (
    <div className="mt-6 rounded-xl border-2 border-[#4ADE80]/30 bg-[#4ADE80]/5 p-4">
      <div className="flex items-start justify-between flex-wrap gap-2 mb-3">
        <div>
          <h3 className="text-white/85 text-xs uppercase tracking-widest font-bold">
            5-fold cross-validation
          </h3>
          <p className="text-white/55 text-[11px] mt-0.5 max-w-2xl">
            Post-calibration residual on held-out folds. Smaller = more reliable
            calibration; large ± std = the curve is fitting noise.
          </p>
        </div>
        <div className="text-right">
          <div className="text-[10px] uppercase tracking-widest text-white/45 font-bold">
            Global held-out residual
          </div>
          <div
            className="font-mono text-2xl font-black tabular-nums"
            style={{ color: residualColor(globalAbs) }}
          >
            {cv.globalMeanResidual >= 0 ? "+" : ""}
            {(cv.globalMeanResidual * 100).toFixed(2)}%
            <span className="text-white/45 text-sm font-bold">
              {" "}
              ± {(cv.globalStdResidual * 100).toFixed(2)}%
            </span>
          </div>
        </div>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-xs font-mono">
          <thead className="text-white/45 text-[10px] uppercase tracking-widest font-bold">
            <tr>
              <th className="text-left py-1.5">Bucket</th>
              <th className="text-right py-1.5">Mean residual</th>
              <th className="text-right py-1.5">±std</th>
              <th className="text-right py-1.5">Avg fold n</th>
            </tr>
          </thead>
          <tbody>
            {cv.buckets.map((b) => {
              const avgN = Math.round(
                b.foldNs.reduce((a, n) => a + n, 0) / Math.max(1, b.foldNs.length),
              );
              return (
                <tr key={b.range} className="border-t border-white/5">
                  <td className="py-1.5 text-white/75">{b.range}</td>
                  <td
                    className="text-right py-1.5 font-bold"
                    style={{ color: residualColor(b.meanResidual) }}
                  >
                    {b.meanResidual >= 0 ? "+" : ""}
                    {(b.meanResidual * 100).toFixed(2)}%
                  </td>
                  <td className="text-right py-1.5 text-white/55">
                    {(b.stdResidual * 100).toFixed(2)}%
                  </td>
                  <td className="text-right py-1.5 text-white/45">{avgN.toLocaleString()}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// ════════════════════════════════════════════════════════════════════
// Walk-forward drift chart — shows how the calibration's bias evolves
// across months as the training set grows. Pure SVG, no chart library.
// ════════════════════════════════════════════════════════════════════

function WalkForwardSection({ wf }: { wf: WalkForwardData }) {
  const months = wf.months;
  // Auto-zoom Y range with 25% headroom; floor at ±1% so a near-perfect run
  // doesn't show as a flat line at the top.
  const dataMaxAbs = Math.max(...months.map((m) => Math.abs(m.residual)));
  const yMax = Math.max(0.01, Math.ceil(dataMaxAbs * 125) / 100);
  const maxTrainSize = Math.max(...months.map((m) => m.trainSize));

  // Layout — two stacked panels, generous spacing.
  const W = 880;
  const padL = 64;
  const padR = 24;
  const padT = 28;
  const residualH = 220; // upper panel
  const gap = 18;
  const barsH = 96; // lower panel
  const xLabelH = 36;
  const H = padT + residualH + gap + barsH + xLabelH;

  const plotW = W - padL - padR;
  const xFor = (i: number) =>
    padL + (months.length === 1 ? plotW / 2 : (i / (months.length - 1)) * plotW);

  // Residual panel (centered on zero)
  const residualTop = padT;
  const residualMid = residualTop + residualH / 2;
  const yResidualFor = (residual: number) =>
    residualMid - (residual / yMax) * (residualH / 2 - 14);

  // Bars panel
  const barsTop = padT + residualH + gap;
  const barsBaseline = barsTop + barsH - 18;
  const barsCeiling = barsTop + 6;
  const barH = (size: number) =>
    (size / maxTrainSize) * (barsBaseline - barsCeiling);

  // Build line + filled area
  const linePoints = months.map((m, i) => `${xFor(i).toFixed(1)},${yResidualFor(m.residual).toFixed(1)}`);
  const linePath = `M ${linePoints.join(" L ")}`;
  const zeroY = yResidualFor(0);
  const areaPath = `M ${xFor(0).toFixed(1)},${zeroY} L ${linePoints.join(" L ")} L ${xFor(months.length - 1).toFixed(1)},${zeroY} Z`;

  // Y ticks: -yMax, -yMax/2, 0, yMax/2, yMax
  const yTicks = [yMax, yMax / 2, 0, -yMax / 2, -yMax];
  const monthLabel = (ym: string) => {
    const [, mm] = ym.split("-");
    return ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][
      parseInt(mm, 10)
    ];
  };
  const yearShort = (ym: string) => `'${ym.slice(2, 4)}`;

  return (
    <div className="mt-6 rounded-2xl border border-[#00F5D4]/30 bg-gradient-to-br from-[#00F5D4]/[0.07] to-transparent p-5">
      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-3 mb-4">
        <div className="flex-1 min-w-[260px]">
          <div className="text-[10px] uppercase tracking-[0.18em] text-[#00F5D4]/80 font-bold mb-1">
            Walk-forward drift
          </div>
          <h3 className="text-white text-xl font-[family-name:var(--font-heading)] font-black leading-tight">
            Calibration residual as data accumulates
          </h3>
          <p className="text-white/55 text-xs mt-1.5 max-w-xl leading-relaxed">
            Each month, the calibrator is retrained on every prior month, then evaluated on
            that month&apos;s picks. The lower bars show the training-set size — drift shrinks
            as the dataset grows.
          </p>
        </div>
        <div className="rounded-xl bg-[#0D0D1A]/70 border border-white/10 px-4 py-3 text-right">
          <div className="text-[10px] uppercase tracking-widest text-white/45 font-bold">
            Mean |residual|
          </div>
          <div
            className="font-mono text-3xl font-black tabular-nums leading-none mt-1"
            style={{ color: residualColor(wf.meanAbsResidual) }}
          >
            {(wf.meanAbsResidual * 100).toFixed(2)}%
          </div>
          <div className="text-[10px] text-white/45 mt-1">
            across {months.length} months
          </div>
        </div>
      </div>

      {/* Chart */}
      <div className="rounded-xl bg-[#0D0D1A] border border-white/10 p-3">
        <svg
          viewBox={`0 0 ${W} ${H}`}
          className="w-full h-auto"
          preserveAspectRatio="xMidYMid meet"
          role="img"
          aria-label="Walk-forward residual line above training-set-size bars, per month"
        >
          <defs>
            <linearGradient id="wfAreaPos" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#FF3AF2" stopOpacity="0.35" />
              <stop offset="100%" stopColor="#FF3AF2" stopOpacity="0" />
            </linearGradient>
            <linearGradient id="wfBar" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#00F5D4" stopOpacity="0.85" />
              <stop offset="100%" stopColor="#00F5D4" stopOpacity="0.25" />
            </linearGradient>
          </defs>

          {/* ── Panel A: Residual ─────────────────────────────────── */}
          {/* Panel label */}
          <text
            x={padL}
            y={padT - 10}
            fill="rgba(255,255,255,0.5)"
            fontSize="10"
            fontFamily="monospace"
            fontWeight="700"
            letterSpacing="0.12em"
          >
            RESIDUAL  (actual − predicted, post-calibration)
          </text>

          {/* Y gridlines + labels */}
          {yTicks.map((t) => {
            const y = yResidualFor(t);
            const isZero = Math.abs(t) < 1e-9;
            return (
              <g key={`yt-${t}`}>
                <line
                  x1={padL}
                  x2={W - padR}
                  y1={y}
                  y2={y}
                  stroke={isZero ? "rgba(255,255,255,0.4)" : "rgba(255,255,255,0.07)"}
                  strokeDasharray={isZero ? "0" : "2 4"}
                  strokeWidth={isZero ? 1.25 : 1}
                />
                <text
                  x={padL - 10}
                  y={y + 3.5}
                  textAnchor="end"
                  fill={isZero ? "rgba(255,255,255,0.6)" : "rgba(255,255,255,0.4)"}
                  fontSize="10"
                  fontFamily="monospace"
                >
                  {isZero ? "0" : `${t > 0 ? "+" : ""}${(t * 100).toFixed(1)}%`}
                </text>
              </g>
            );
          })}

          {/* Area fill */}
          <path d={areaPath} fill="url(#wfAreaPos)" />

          {/* Residual line */}
          <path
            d={linePath}
            fill="none"
            stroke="#FF3AF2"
            strokeWidth={2.25}
            strokeLinejoin="round"
            strokeLinecap="round"
          />

          {/* Data points + value labels (alternating above/below to dodge the line) */}
          {months.map((m, i) => {
            const x = xFor(i);
            const y = yResidualFor(m.residual);
            const labelAbove = m.residual >= 0;
            const labelY = labelAbove ? y - 12 : y + 18;
            return (
              <g key={`pt-${m.month}`}>
                <circle cx={x} cy={y} r={6} fill="#0D0D1A" stroke={residualColor(m.residual)} strokeWidth={2.5} />
                <circle cx={x} cy={y} r={2.5} fill={residualColor(m.residual)} />
                <text
                  x={x}
                  y={labelY}
                  textAnchor="middle"
                  fill={residualColor(m.residual)}
                  fontSize="11"
                  fontFamily="monospace"
                  fontWeight="700"
                >
                  {m.residual >= 0 ? "+" : ""}
                  {(m.residual * 100).toFixed(1)}%
                </text>
              </g>
            );
          })}

          {/* ── Panel B: Training-set bars ───────────────────────── */}
          {/* Panel label */}
          <text
            x={padL}
            y={barsTop - 6}
            fill="rgba(255,255,255,0.5)"
            fontSize="10"
            fontFamily="monospace"
            fontWeight="700"
            letterSpacing="0.12em"
          >
            TRAINING SET SIZE  (cumulative pairs before this month)
          </text>

          {/* Baseline */}
          <line
            x1={padL}
            x2={W - padR}
            y1={barsBaseline}
            y2={barsBaseline}
            stroke="rgba(255,255,255,0.15)"
            strokeWidth={1}
          />

          {/* Bars */}
          {months.map((m, i) => {
            const x = xFor(i);
            const h = barH(m.trainSize);
            const w = 22;
            return (
              <g key={`bar-${m.month}`}>
                <rect
                  x={x - w / 2}
                  y={barsBaseline - h}
                  width={w}
                  height={h}
                  rx={3}
                  fill="url(#wfBar)"
                />
                <text
                  x={x}
                  y={barsBaseline - h - 4}
                  textAnchor="middle"
                  fill="rgba(0,245,212,0.85)"
                  fontSize="9"
                  fontFamily="monospace"
                  fontWeight="700"
                >
                  {m.trainSize >= 1000
                    ? `${(m.trainSize / 1000).toFixed(m.trainSize >= 100000 ? 0 : 1)}k`
                    : m.trainSize.toString()}
                </text>
              </g>
            );
          })}

          {/* X-axis month labels (shared between panels) */}
          {months.map((m, i) => {
            const x = xFor(i);
            const showYear = i === 0 || m.month.slice(0, 4) !== months[i - 1].month.slice(0, 4);
            return (
              <g key={`xlabel-${m.month}`}>
                <text
                  x={x}
                  y={barsBaseline + 16}
                  textAnchor="middle"
                  fill="rgba(255,255,255,0.65)"
                  fontSize="11"
                  fontFamily="monospace"
                  fontWeight="600"
                >
                  {monthLabel(m.month)}
                </text>
                {showYear && (
                  <text
                    x={x}
                    y={barsBaseline + 30}
                    textAnchor="middle"
                    fill="rgba(255,255,255,0.4)"
                    fontSize="9.5"
                    fontFamily="monospace"
                  >
                    {yearShort(m.month)}
                  </text>
                )}
              </g>
            );
          })}
        </svg>
      </div>

      {/* Legend / context strip */}
      <div className="mt-3 flex flex-wrap items-center gap-4 text-[11px]">
        <div className="flex items-center gap-2">
          <span
            className="inline-block w-3 h-[2px] rounded"
            style={{ backgroundColor: "#FF3AF2" }}
            aria-hidden
          />
          <span className="text-white/65">Residual (Δ from zero)</span>
        </div>
        <div className="flex items-center gap-2">
          <span
            className="inline-block w-3 h-3 rounded-sm bg-[#00F5D4]/60"
            aria-hidden
          />
          <span className="text-white/65">Training pairs (max {(maxTrainSize / 1000).toFixed(0)}k)</span>
        </div>
        <div className="ml-auto flex items-center gap-3 text-white/45">
          <span className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-[#4ADE80]" /> &lt;2%
          </span>
          <span className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-[#FFE600]" /> 2–5%
          </span>
          <span className="flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-[#F87171]" /> ≥5%
          </span>
        </div>
      </div>

      {/* Per-month table for accessibility / detail */}
      <details className="mt-2">
        <summary className="text-[10px] uppercase tracking-widest text-white/45 font-bold cursor-pointer hover:text-white/65">
          Per-month detail
        </summary>
        <div className="mt-2 overflow-x-auto">
          <table className="w-full text-xs font-mono">
            <thead className="text-white/45 text-[10px] uppercase tracking-widest font-bold">
              <tr>
                <th className="text-left py-1.5">Month</th>
                <th className="text-right py-1.5">Train size</th>
                <th className="text-right py-1.5">Eval size</th>
                <th className="text-right py-1.5">Predicted</th>
                <th className="text-right py-1.5">Actual</th>
                <th className="text-right py-1.5">Residual</th>
              </tr>
            </thead>
            <tbody>
              {months.map((m) => (
                <tr key={m.month} className="border-t border-white/5">
                  <td className="py-1.5 text-white/75">{m.month}</td>
                  <td className="text-right py-1.5 text-white/55">
                    {m.trainSize.toLocaleString()}
                  </td>
                  <td className="text-right py-1.5 text-white/55">
                    {m.evalSize.toLocaleString()}
                  </td>
                  <td className="text-right py-1.5 text-white/75">
                    {(m.meanPredicted * 100).toFixed(1)}%
                  </td>
                  <td className="text-right py-1.5 text-white/75">
                    {(m.actualHitRate * 100).toFixed(1)}%
                  </td>
                  <td
                    className="text-right py-1.5 font-bold"
                    style={{ color: residualColor(m.residual) }}
                  >
                    {m.residual >= 0 ? "+" : ""}
                    {(m.residual * 100).toFixed(2)}%
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </details>
    </div>
  );
}

