import { registerAdapter } from "./registry";
import { nbaAdapter } from "./nba";
registerAdapter(nbaAdapter);
import { wnbaAdapter } from "./wnba";
registerAdapter(wnbaAdapter);
import { mlbAdapter } from "./mlb";
registerAdapter(mlbAdapter);
import { nflAdapter } from "./nfl";
registerAdapter(nflAdapter);
import { nhlAdapter } from "./nhl";
registerAdapter(nhlAdapter);
import { soccerAdapter } from "./soccer";
registerAdapter(soccerAdapter);
import { tennisAdapter } from "./tennis";
registerAdapter(tennisAdapter);
import { pgaAdapter } from "./pga";
registerAdapter(pgaAdapter);
import { aflAdapter } from "./afl";
registerAdapter(aflAdapter);
